---
title: " Multilevel Modelling, MLM "
author: "Wen Chi"
date: "2025-06-16"
categories: [notes, analysis]
---

MLM also has some synonyms or derivative models in different fields:

-   Hierarchical Linear Model,HLM

-   Linear Mixed Model

-   Mixed Effects Model

-   Random Effects Model

-   Random Coefficients Model

-   Variance Components Model

-   Growth Curve Model

Regression analysis is the basis of almost all statistical models, and the most general form of regression analysis can be classified as the multilevel linear model HLM.

-   The t-test is a special case of ANOVA (the independent variable has only two levels)

-   ANOVA is a special case of regression analysis (independent variables are categorical variables)

-   The essence of regression analysis is the general linear model GLM (generalized linear model by extension)

-   GLM is a special case of HLM (Level 1 only)

-   Meta-analysis can be viewed as HLM with only group models (Level 2 only)

Distinguish "multilevel linear models" from "hierarchical/stepwise multiple regression" :

-   Multilevel linear model solves multi-layer nested structure data (the end point is the data structure)

-   Hierarchical/stepwise multiple regression itself is an ordinary regression analysis, which solves the priority of the importance of different independent variables (the goal is the importance of variables).
